### ISSUE TITLE
docker-socket-path option needs to receive a string

### ISSUE THREAD

**Issue by MaxReimann** [edge/cli#90]
Docker on Windows/WSL2 needs to connect via sockets. The --docker-socket-path option is boolean, however it seems to expect a string:

```
edge --docker-socket-path --debug device add   
[device] connected to Docker {
  "options": {
    "socketPath": "true"
  }
}
[critical] TypeError [ERR_INVALID_ARG_TYPE]: The "options.path" property must be of type string. Received type boolean (true) {
  "err": {
    "message": "The \"options.path\" property must be of type string. Received type boolean (true)",
    "name": "TypeError",
    "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"options.path\" property must be of type string. Received type boolean (true)\n    at validateString (internal/validators.js:124:11)\n    at Socket.connect (net.js:973:5)\n    at Agent.connect [as createConnection] (net.js:189:17)\n    at Agent.createSocket (_http_agent.js:323:26)\n    at Agent.addRequest (_http_agent.js:274:10)\n    at new ClientRequest (_http_client.js:305:16)\n    at Object.request (http.js:94:10)\n    at h.request (C:\\snapshot\\cli\\node_modules\\docker-modem\\lib\\http.js:51:52)\n    at Modem.buildRequest (C:\\snapshot\\cli\\node_modules\\docker-modem\\lib\\modem.js:239:68)\n    at Modem.dial (C:\\snapshot\\cli\\node_modules\\docker-modem\\lib\\modem.js:222:8)"
  }
```

**Comment by annybs** [comment]
Apologies for the inconvenience. This is fixed in the course of https://github.com/edge/cli/pull/92 and released to testnet in 1.5.1. This should be updated on mainnet soon.
